-- Buat skema SALAM
CREATE SCHEMA SALAM;
-- Buat tabel mahasiswas
CREATE TABLE SALAM.mahasiswas (
    id SERIAL PRIMARY KEY,
    nim VARCHAR(20) UNIQUE NOT NULL,
    nama VARCHAR(100) NOT NULL,
    umur INT CHECK (
        umur >= 17
        AND umur <= 30
    ),
    email VARCHAR(100) UNIQUE NOT NULL
);
-- Buat user backend_dev dengan role CRUD
CREATE USER backend_dev WITH PASSWORD 'backend123';
GRANT CONNECT ON DATABASE postgres TO backend_dev;
GRANT USAGE ON SCHEMA SALAM TO backend_dev;
GRANT SELECT,
    INSERT,
    UPDATE,
    DELETE ON ALL TABLES IN SCHEMA SALAM TO backend_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM
GRANT SELECT,
    INSERT,
    UPDATE,
    DELETE ON TABLES TO backend_dev;
-- Buat user bi_dev dengan role hanya SELECT
CREATE USER bi_dev WITH PASSWORD 'bi123';
GRANT CONNECT ON DATABASE postgres TO bi_dev;
GRANT USAGE ON SCHEMA SALAM TO bi_dev;
GRANT SELECT ON ALL TABLES IN SCHEMA SALAM TO bi_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM
GRANT SELECT ON TABLES TO bi_dev;
-- Buat user data_engineer dengan role penuh
CREATE USER data_engineer WITH PASSWORD 'engineer123';
GRANT CONNECT ON DATABASE postgres TO data_engineer;
GRANT ALL PRIVILEGES ON SCHEMA SALAM TO data_engineer;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA SALAM TO data_engineer;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA SALAM TO data_engineer;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM
GRANT ALL ON TABLES TO data_engineer;
ALTER DEFAULT PRIVILEGES IN SCHEMA SALAM
GRANT ALL ON SEQUENCES TO data_engineer;